In [1]:
import torch 

In [2]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [3]:
batch_t = torch.randn(2, 3, 5, 5)

In [4]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [5]:
weights.shape

torch.Size([3])

In [6]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [7]:
img_weights = (img_t * unsqueezed_weights) 
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weights = img_weights.sum(-3)
batch_gray_weights = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [8]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short 

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [11]:
some_t = torch.randn(1, 3, 2)
some_t

tensor([[[ 0.1380, -0.2581],
         [-1.5983,  1.2176],
         [-1.1406,  0.1478]]])

In [12]:
transpose_t = some_t.transpose(0, 2)
transpose_t

tensor([[[ 0.1380],
         [-1.5983],
         [-1.1406]],

        [[-0.2581],
         [ 1.2176],
         [ 0.1478]]])